
// src/fonts/customFonts.js

export const dejavuserif = {
  name: "dejavuserif",
  style: "normal",
  data: "AAEAAAALAIAAAwAwT1MvMg8SbiwAAAC8AAAAYGNtYXABd0TmAAABHAAAAExnYXNwAAAAEAAAAXgAAAAIZ2x5ZrJUGJgAAAIkAAABOmhlYWQZFGhRAAACbAAAADZoaGVhBhIGDgAAAnwAAAAkaG10eFcUAAAAAAKMAAAAEGxvY2EHgAAAAAACkAAAACRtYXhwAAUAEAAAArwAAAAgbmFtZZPZET0AAALUAAABznBvc3QAAwAAAAADAgAAAAMAAQAAAwAAAAEAAAAAAAAAAQAAAAAAAAAAAAAAAAAAABk="
};
